service: templatebuilder365-dynamodb

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'stage'}
  deploymentBucket:
    name: tb365-serverless-deployments-stage

custom:
  tableName: TemplateBuilder365-Data-${self:provider.stage}

resources:
  Resources:
    # Unified DynamoDB Table for Images, Users, Projects, Admin (Single Table Design)
    TemplateBuilder365DataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST

        AttributeDefinitions:
          # Primary key attributes
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S

          # GSI1: Image and project tag search
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S

          # GSI2: User and entity type queries
          - AttributeName: GSI2PK
            AttributeType: S
          - AttributeName: GSI2SK
            AttributeType: S

          # GSI3: Admin and system-wide queries
          - AttributeName: GSI3PK
            AttributeType: S
          - AttributeName: GSI3SK
            AttributeType: S

        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE

        GlobalSecondaryIndexes:
          # GSI1: Tag-based search for images and projects
          - IndexName: TagSearchIndex
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

          # GSI2: Entity type and user-based queries
          - IndexName: EntityTypeIndex
            KeySchema:
              - AttributeName: GSI2PK
                KeyType: HASH
              - AttributeName: GSI2SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

          # GSI3: Admin and system-wide analytics
          - IndexName: SystemIndex
            KeySchema:
              - AttributeName: GSI3PK
                KeyType: HASH
              - AttributeName: GSI3SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: TemplateBuilder365
          - Key: Component
            Value: Database
          - Key: Purpose
            Value: unified-data-storage

  Outputs:
    DynamoDBTableName:
      Description: DynamoDB table name for TemplateBuilder365
      Value: ${self:custom.tableName}
      Export:
        Name: TemplateBuilder365-Table-${self:provider.stage}

    DynamoDBTableArn:
      Description: DynamoDB table ARN
      Value:
        Fn::GetAtt:
          - TemplateBuilder365DataTable
          - Arn
      Export:
        Name: TemplateBuilder365-TableArn-${self:provider.stage}

    TagSearchIndexName:
      Description: GSI1 for tag-based search
      Value: TagSearchIndex
      Export:
        Name: TemplateBuilder365-TagSearchIndex-${self:provider.stage}

    EntityTypeIndexName:
      Description: GSI2 for entity type queries
      Value: EntityTypeIndex
      Export:
        Name: TemplateBuilder365-EntityTypeIndex-${self:provider.stage}

    SystemIndexName:
      Description: GSI3 for admin/system queries
      Value: SystemIndex
      Export:
        Name: TemplateBuilder365-SystemIndex-${self:provider.stage}