service: tb365-html-converter

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: stage
  deploymentBucket:
    name: tb365-serverless-deployments-stage
  environment:
    STAGE: ${self:provider.stage}
    NODE_ENV: ${self:provider.stage}
    COGNITO_USER_POOL_ID: us-east-1_RIOPGg1Cq
    COGNITO_CLIENT_ID: 2addji24p0obg5sqedgise13i4
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      maxAge: 300
    authorizers:
      cognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_RIOPGg1Cq
        audience:
          - 2addji24p0obg5sqedgise13i4

functions:
  convertToHtml:
    handler: handler.convertToHtml
    timeout: 25
    memorySize: 256
    events:
      - httpApi:
          path: /convert
          method: post
          authorizer:
            name: cognitoAuthorizer

  health:
    handler: handler.health
    events:
      - httpApi:
          path: /health
          method: get

package:
  patterns:
    - '!node_modules/**'
    - 'node_modules/@aws-sdk/**'
    - 'node_modules/joi/**'
    - 'node_modules/uuid/**'